### ISSUE TITLE
Additional runs on 8.29.2018

### ISSUE THREAD

**Issue by donahuem** [lizzieinvancouver/temporalvar#17]
Another set of runs:
51995069:  tracking=1, varRstar=1, vartauI=1; ran 50 tasks or 150 runs in the array; about half of the tasks completed (others ran out of mem).  [note that RunParms file is missing because the task that would have written it failed - will change this dependency]
51995121: tracking=1, varRstar =1, vartauI=0; all 50 tasks of 150 runs completed
51995125: tracking=0, varRstar=1,vartauI=1; all 50 tasks of 150 completed
51995137: tracking=1, varRstar=0, vartauI=1; ran 50 tasks or 150 runs in the array; about half of the tasks completed (others ran out of mem).  [note that RunParms file is missing because the task that would have written it failed - will change this dependency]

**Comment by lizzieinvancouver** [comment]
Umm, just to make my life easier for now I relabelled 51995069-2 as 51995069-1 (since 51995069-1 failed).

**Comment by lizzieinvancouver** [comment]
And 51995137-6 as 51995137-1...

**Comment by lizzieinvancouver** [comment]
I have added these to the analyses code!
