### ISSUE TITLE
add Bfin slopes and rerun

### ISSUE THREAD

**Issue by donahuem** [lizzieinvancouver/temporalvar#38]
Need to add a slope over the last 100 yrs and maybe a growth rate measure based on multiplicative rate of increase for the last 100 yrs to the summary output

Send new runs with these conditions

**Comment by donahuem** [comment]
Added SummaryOut:  
-slope of linear regression for the period (i.e., stationary or nonstationary), excluding the first 10 years, if there are 10 or more years in the period
-average(ln(N(t)/N(t-1)) for the period, excluding the first 10 years to avoid effect of initial conditions; does not calculate if there are less than 10 years in the period.

**Comment by donahuem** [comment]
@lizzieinvancouver 
First set of runs with these additional outputs.  
Submitted batch job 62025212
Submitted batch job 62025233
Submitted batch job 62025263
Submitted batch job 62025274

**Comment by lizzieinvancouver** [comment]
@donahuem Nice! I pulled these and can work on plots with a little help. The files no longer have header rows that say what each column is so can you let me know what the last 12 columns names are? (I assume the first columns through tauIPmean are unchanged, but let me know if that assumption is incorrect). Thanks!

**Comment by lizzieinvancouver** [comment]
@donahuem Wait! One more issue (sorry); the files also have: 

```
#NAME?
--
```
In some of the cells (line 7 of SummaryOut_62025212-1.txt for example) and that is tricky to read in. Can we clean these up somehow in the creation script? I will see if I can figure a workaround for now....

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Me again! So I can read the files with the #NAME in them but the first one I looked at is odd: it says no two-species coexistence in period 1, but there is maybe 20 rows with two-species coexistence in period 2 ... which is odd. Maybe I have the column headers wrong ... will await further instructions.

**Comment by lizzieinvancouver** [comment]
Update: the #NAME? is an issue Lizzie added ... in opening and saving the files in Excel (just this file: SummaryOut_62025212-1.txt) she probably made all the -Inf values into #NAME?.

@lizzieinvancouver So ignore the #NAME? but Lizzie should re download: SummaryOut_62025212-1.txt

**Comment by lizzieinvancouver** [comment]
colnames are: jobID	taskID	runID	period	nperiods	yout	itertime	ncoexist	coexist1	coexist2	alpha1	alpha2	c1	c2	Rstar1	Rstar2	tauI1	tauI2	g1mean	g2mean	tauIP1_mean	tauIP2_mean	wetID	dryID	row	R0_mean	R0_media	R0_autocorr	Bfin1	Bfin2	slope_Bfin1	slope_Bfin2	avgPCgrowth1	avgPCgrowth1

**Comment by donahuem** [comment]
OK, I think i fixed output so that each period should print out and header is only at the top.  Note that I added output columns for s_1, s_2, phi_1, phi_2

**Comment by donahuem** [comment]
Next batch of runs that I am trying for regular runs:  
855518
855569
855591
855642

**Comment by donahuem** [comment]
When you have a chance to look at the output, can you check how frequently the "slopeBfin" and "avgPCgrowth" (last two columns) are NA or Inf.

**Comment by lizzieinvancouver** [comment]
SlopeBfin is never NA or -Inf, but avgPCgrowth is 60% of the time.
