### ISSUE TITLE
check recent runs

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/temporalvar#40]
Cannot find any coexisting runs in period 1 ... for example, see this which has ONLY period 2:

```
subset(df.all, jobID=="62025212" & taskID=="10" & runID=="12") 
subset(df.all, jobID=="62025274" & taskID=="35" & runID=="81") 


goo <- subset(df.all, ncoexist==2)

unique(goo$period)
```

**Comment by lizzieinvancouver** [comment]
@donahuem In working on megadrought runs, I am seeing the same issue.

**Comment by donahuem** [comment]
New set of runs!  5 cases:
858179 - tradeoff R*, tracking, tauI
858221 - tradeoff R* and tracking
858241 - tradeoiff R* and tauI
858262 - tradeoff tracking and tauI with R* equal
858282 - tradeoff R* and tracking with declining R0

**Comment by donahuem** [comment]
Added another set of megaD runs:
858363 - low tauI
858372 - mod tauI
858373 - hi tauI

**Comment by donahuem** [comment]
Next two batches of normal runs (including a declining R0 run)
888288
888338
888369
888380
888430
---------
888600
888602
888605
888607
888608

Next batch of megaD runs
888547
888549
888556

**Comment by donahuem** [comment]
Next batch of runs (5 types)
933059
933107
933156
933215
933272
________
933566
933600
933630
933682
933723

**Comment by donahuem** [comment]
Starting next batch of runs (5 types)
988487
988653
988808
988912
989020
