### ISSUE TITLE
Work on some estimates for R0 runs

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/temporalvar#42]
To do on this:

1. Plots don't show anything super dramatic ... but could stare at longer. 
2. Need to estimate the distribution of R* and alpha of winners after NS period in runs with R0 declining and those with without changes in R0. We expect declining R0 may slightly reduce winners via alpha.

**Comment by lizzieinvancouver** [comment]
Okay, so I assume there is a typo in 2. above `with without' I think means `without' since we just have runs with declining R0 (alphaRstarR0.runs in my R script) and runs without declining R0 (alphaRstarR0). 

No dramatic differences found yet ....

```
> mean(c(alphaRstar.calc.df$Rstar1, alphaRstar.calc.df$Rstar2), na.rm=TRUE)
[1] 0.0001652541
> mean(c(alphaRstarR0.calc.df$Rstar1, alphaRstarR0.calc.df$Rstar2), na.rm=TRUE)
[1] 0.0001638471
> mean(c(alphaRstar.calc.df$alpha1, alphaRstar.calc.df$alpha2), na.rm=TRUE)
[1] 0.7692643
> mean(c(alphaRstarR0.calc.df$alpha1, alphaRstarR0.calc.df$alpha2), na.rm=TRUE)
[1] 0.7683217

```
But I will do some plotting also .... (plot ncoexist=2 for stat from R0 and non-R0 runs on top of one another and do the same for non-stat).

**Comment by lizzieinvancouver** [comment]
**First** though, I should plot R0 from envrt params files ... !

**Comment by donahuem** [comment]
Started more declining R0 runs.  Job IDs are 8995922, 8995924

**Comment by lizzieinvancouver** [comment]
Runparms file: R0ns_flag takes a value and that value is multipled by mean ... the 8995922, 8995924 have it at 0.25 ... so 75% decline in R (previous runs were 50%).

**Comment by lizzieinvancouver** [comment]
Next up: do overlay plots, see the source code and search for START HERE

**Comment by lizzieinvancouver** [comment]
This is all done ...
Here are the R* values of all remaining species after nonstationary period:

1.  0.000164768 (earlier tauP only)
2. 0.0001638775 (earlier tauP and 50% R0 decline)
3. 0.0001630809 (earlier tauP and 75% R0 decline)

And the alpha values:

1.  0.769729 (earlier tauP only)
2. 0.7692253 (earlier tauP and 50% R0 decline)
3. 0.7719409 (earlier tauP and 75% R0 decline)

So when two things decline, alphas go up (better tracking) and R* goes down (better competitors): Why? As Megan thought, things go extinct faster with declines in R0:

Here's the percent of species surviving after nonstationary (# species surviving after nonstationary/# species surviving after stationary):
1.  0.5023858 (earlier tauP only)
2. 0.4921753 (earlier tauP and 50% R0 decline)
3. 0.4697856 (earlier tauP and 75% R0 decline)

**Comment by lizzieinvancouver** [comment]
Oh, and the plots are in graphs/paramdiffs/decliningR0
