### ISSUE TITLE
Reverse relationship between germination timing and chilling

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/temporalvar#50]
day of 50% germination should DECREASE with increasing chilling. We can justify saying that the maximum delay is 90 days and minimum is 0 days.  generally mean delays could be 0-30 days.

**Comment by donahuem** [comment]
Made it so mean delay in germination (defined by day of 50%germ) declines exponentially from 30 to 0 at rate tau_xi.  A poisson distribution with this mean determines the actual days of delay in any particular season.
