### ISSUE TITLE
Make flags or % for germination fraction sensitivity  patterns

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/temporalvar#51]
#UPDATE: create a flag (or 25% of runs) where both %g is insensitive for both species
#   and both same %g_max = 0.8 -- these will allow comparison of timing-only effects

**Comment by donahuem** [comment]
Made 20% of runs where both species are chilling insensitive with respect to %germination.

Of the remaining 80% of runs, 
20% x 20% = 4% will have both species chilling insensitive with varying gmax (between 0.5-1)
20% + 20% = 40% will have one or the other species chilling insensitive with varying gmax [0.5,1]
1-40%-4% = 56% will have both species chilling-sensitive wrt gmax
